/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnnouncementId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const AnnouncementPublic = IDL.Record({
  'id' : AnnouncementId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const Result_11 = IDL.Variant({
  'ok' : AnnouncementPublic,
  'err' : IDL.Text,
});
export const CourseId = IDL.Nat;
export const AssignmentId = IDL.Nat;
export const AssignmentPublic = IDL.Record({
  'id' : AssignmentId,
  'title' : IDL.Text,
  'maxPoints' : IDL.Nat,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'dueDate' : IDL.Opt(Timestamp),
  'description' : IDL.Text,
  'courseId' : IDL.Opt(CourseId),
});
export const Result_10 = IDL.Variant({
  'ok' : AssignmentPublic,
  'err' : IDL.Text,
});
export const CoursePublic = IDL.Record({
  'id' : CourseId,
  'title' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Result_9 = IDL.Variant({ 'ok' : CoursePublic, 'err' : IDL.Text });
export const LessonId = IDL.Nat;
export const LessonPublic = IDL.Record({
  'id' : LessonId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'order' : IDL.Nat,
  'createdAt' : Timestamp,
  'courseId' : CourseId,
});
export const Result_8 = IDL.Variant({ 'ok' : LessonPublic, 'err' : IDL.Text });
export const NoteId = IDL.Nat;
export const NotePublic = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'updatedAt' : Timestamp,
  'courseId' : IDL.Opt(CourseId),
});
export const Result_7 = IDL.Variant({ 'ok' : NotePublic, 'err' : IDL.Text });
export const QuizId = IDL.Nat;
export const QuestionId = IDL.Nat;
export const QuestionPublic = IDL.Record({
  'id' : QuestionId,
  'text' : IDL.Text,
  'quizId' : QuizId,
  'options' : IDL.Vec(IDL.Text),
});
export const Result_6 = IDL.Variant({
  'ok' : QuestionPublic,
  'err' : IDL.Text,
});
export const QuizPublic = IDL.Record({
  'id' : QuizId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
  'courseId' : CourseId,
});
export const Result_5 = IDL.Variant({ 'ok' : QuizPublic, 'err' : IDL.Text });
export const ScheduleInput = IDL.Record({
  'day' : IDL.Text,
  'subject' : IDL.Text,
  'teacher' : IDL.Text,
  'timeRange' : IDL.Text,
  'className' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const ScheduleId = IDL.Nat;
export const ScheduleSlotPublic = IDL.Record({
  'id' : ScheduleId,
  'day' : IDL.Text,
  'subject' : IDL.Text,
  'createdAt' : Timestamp,
  'teacher' : IDL.Text,
  'isActive' : IDL.Bool,
  'timeRange' : IDL.Text,
  'className' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const Result_4 = IDL.Variant({
  'ok' : ScheduleSlotPublic,
  'err' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const QuizAttempt = IDL.Record({
  'id' : IDL.Nat,
  'total' : IDL.Nat,
  'studentId' : UserId,
  'answers' : IDL.Vec(IDL.Nat),
  'submittedAt' : Timestamp,
  'score' : IDL.Nat,
  'quizId' : QuizId,
});
export const StudentPerformance = IDL.Record({
  'totalEnrollments' : IDL.Nat,
  'studentId' : UserId,
  'studentName' : IDL.Text,
  'averageQuizScore' : IDL.Float64,
  'completedLessons' : IDL.Nat,
  'quizzesTaken' : IDL.Nat,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
});
export const QuestionWithAnswer = IDL.Record({
  'id' : QuestionId,
  'answerIndex' : IDL.Nat,
  'text' : IDL.Text,
  'quizId' : QuizId,
  'options' : IDL.Vec(IDL.Text),
});
export const Result_3 = IDL.Variant({
  'ok' : IDL.Vec(QuestionWithAnswer),
  'err' : IDL.Text,
});
export const Result_2 = IDL.Variant({
  'ok' : UserProfilePublic,
  'err' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : QuizAttempt, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [Result_11], []),
  'createAssignment' : IDL.Func(
      [IDL.Opt(CourseId), IDL.Text, IDL.Text, IDL.Opt(Timestamp), IDL.Nat],
      [Result_10],
      [],
    ),
  'createCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_9], []),
  'createLesson' : IDL.Func(
      [CourseId, IDL.Text, IDL.Text, IDL.Nat],
      [Result_8],
      [],
    ),
  'createNote' : IDL.Func(
      [IDL.Opt(CourseId), IDL.Text, IDL.Text],
      [Result_7],
      [],
    ),
  'createQuestion' : IDL.Func(
      [QuizId, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [Result_6],
      [],
    ),
  'createQuiz' : IDL.Func([CourseId, IDL.Text, IDL.Text], [Result_5], []),
  'createScheduleSlot' : IDL.Func([ScheduleInput], [Result_4], []),
  'deleteAnnouncement' : IDL.Func([AnnouncementId], [Result], []),
  'deleteAssignment' : IDL.Func([AssignmentId], [Result], []),
  'deleteCourse' : IDL.Func([CourseId], [Result], []),
  'deleteLesson' : IDL.Func([LessonId], [Result], []),
  'deleteNote' : IDL.Func([NoteId], [Result], []),
  'deleteQuestion' : IDL.Func([QuestionId], [Result], []),
  'deleteQuiz' : IDL.Func([QuizId], [Result], []),
  'deleteScheduleSlot' : IDL.Func([ScheduleId], [Result], []),
  'enrollInCourse' : IDL.Func([CourseId], [Result], []),
  'getAdminStats' : IDL.Func(
      [],
      [IDL.Record({ 'totalEnrollments' : IDL.Nat, 'totalStudents' : IDL.Nat })],
      ['query'],
    ),
  'getAssignment' : IDL.Func(
      [AssignmentId],
      [IDL.Opt(AssignmentPublic)],
      ['query'],
    ),
  'getCourse' : IDL.Func([CourseId], [IDL.Opt(CoursePublic)], ['query']),
  'getLesson' : IDL.Func([LessonId], [IDL.Opt(LessonPublic)], ['query']),
  'getMyAttempts' : IDL.Func(
      [IDL.Opt(QuizId)],
      [IDL.Vec(QuizAttempt)],
      ['query'],
    ),
  'getMyCompletedLessons' : IDL.Func([], [IDL.Vec(LessonId)], ['query']),
  'getMyEnrollments' : IDL.Func([], [IDL.Vec(CourseId)], ['query']),
  'getMyPerformance' : IDL.Func([], [IDL.Opt(StudentPerformance)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'getNote' : IDL.Func([NoteId], [IDL.Opt(NotePublic)], ['query']),
  'getQuiz' : IDL.Func([QuizId], [IDL.Opt(QuizPublic)], ['query']),
  'listAnnouncements' : IDL.Func([], [IDL.Vec(AnnouncementPublic)], ['query']),
  'listAssignments' : IDL.Func(
      [IDL.Opt(CourseId)],
      [IDL.Vec(AssignmentPublic)],
      ['query'],
    ),
  'listCourses' : IDL.Func([], [IDL.Vec(CoursePublic)], ['query']),
  'listLessons' : IDL.Func([CourseId], [IDL.Vec(LessonPublic)], ['query']),
  'listNotes' : IDL.Func([IDL.Opt(CourseId)], [IDL.Vec(NotePublic)], ['query']),
  'listQuestions' : IDL.Func([QuizId], [IDL.Vec(QuestionPublic)], ['query']),
  'listQuestionsWithAnswers' : IDL.Func([QuizId], [Result_3], []),
  'listQuizzes' : IDL.Func([CourseId], [IDL.Vec(QuizPublic)], ['query']),
  'listScheduleSlots' : IDL.Func([], [IDL.Vec(ScheduleSlotPublic)], ['query']),
  'listScheduleSlotsByClass' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ScheduleSlotPublic)],
      ['query'],
    ),
  'listStudentPerformances' : IDL.Func(
      [],
      [IDL.Vec(StudentPerformance)],
      ['query'],
    ),
  'listUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
  'markAnnouncementRead' : IDL.Func([AnnouncementId], [Result], []),
  'markLessonComplete' : IDL.Func([LessonId], [Result], []),
  'register' : IDL.Func([IDL.Text], [Result_2], []),
  'registerAsAdmin' : IDL.Func([IDL.Text], [Result_2], []),
  'submitQuizAttempt' : IDL.Func([QuizId, IDL.Vec(IDL.Nat)], [Result_1], []),
  'updateAnnouncement' : IDL.Func(
      [AnnouncementId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
  'updateAssignment' : IDL.Func(
      [
        AssignmentId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(Timestamp),
        IDL.Opt(IDL.Nat),
      ],
      [Result],
      [],
    ),
  'updateCourse' : IDL.Func(
      [
        CourseId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
      ],
      [Result],
      [],
    ),
  'updateLesson' : IDL.Func(
      [LessonId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [Result],
      [],
    ),
  'updateNote' : IDL.Func(
      [NoteId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
  'updateQuestion' : IDL.Func(
      [
        QuestionId,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Text)),
        IDL.Opt(IDL.Nat),
      ],
      [Result],
      [],
    ),
  'updateQuiz' : IDL.Func(
      [QuizId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
  'updateScheduleSlot' : IDL.Func([ScheduleId, ScheduleInput], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnnouncementId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const AnnouncementPublic = IDL.Record({
    'id' : AnnouncementId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const Result_11 = IDL.Variant({
    'ok' : AnnouncementPublic,
    'err' : IDL.Text,
  });
  const CourseId = IDL.Nat;
  const AssignmentId = IDL.Nat;
  const AssignmentPublic = IDL.Record({
    'id' : AssignmentId,
    'title' : IDL.Text,
    'maxPoints' : IDL.Nat,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'dueDate' : IDL.Opt(Timestamp),
    'description' : IDL.Text,
    'courseId' : IDL.Opt(CourseId),
  });
  const Result_10 = IDL.Variant({ 'ok' : AssignmentPublic, 'err' : IDL.Text });
  const CoursePublic = IDL.Record({
    'id' : CourseId,
    'title' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Result_9 = IDL.Variant({ 'ok' : CoursePublic, 'err' : IDL.Text });
  const LessonId = IDL.Nat;
  const LessonPublic = IDL.Record({
    'id' : LessonId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'order' : IDL.Nat,
    'createdAt' : Timestamp,
    'courseId' : CourseId,
  });
  const Result_8 = IDL.Variant({ 'ok' : LessonPublic, 'err' : IDL.Text });
  const NoteId = IDL.Nat;
  const NotePublic = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'updatedAt' : Timestamp,
    'courseId' : IDL.Opt(CourseId),
  });
  const Result_7 = IDL.Variant({ 'ok' : NotePublic, 'err' : IDL.Text });
  const QuizId = IDL.Nat;
  const QuestionId = IDL.Nat;
  const QuestionPublic = IDL.Record({
    'id' : QuestionId,
    'text' : IDL.Text,
    'quizId' : QuizId,
    'options' : IDL.Vec(IDL.Text),
  });
  const Result_6 = IDL.Variant({ 'ok' : QuestionPublic, 'err' : IDL.Text });
  const QuizPublic = IDL.Record({
    'id' : QuizId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
    'courseId' : CourseId,
  });
  const Result_5 = IDL.Variant({ 'ok' : QuizPublic, 'err' : IDL.Text });
  const ScheduleInput = IDL.Record({
    'day' : IDL.Text,
    'subject' : IDL.Text,
    'teacher' : IDL.Text,
    'timeRange' : IDL.Text,
    'className' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const ScheduleId = IDL.Nat;
  const ScheduleSlotPublic = IDL.Record({
    'id' : ScheduleId,
    'day' : IDL.Text,
    'subject' : IDL.Text,
    'createdAt' : Timestamp,
    'teacher' : IDL.Text,
    'isActive' : IDL.Bool,
    'timeRange' : IDL.Text,
    'className' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const Result_4 = IDL.Variant({ 'ok' : ScheduleSlotPublic, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const QuizAttempt = IDL.Record({
    'id' : IDL.Nat,
    'total' : IDL.Nat,
    'studentId' : UserId,
    'answers' : IDL.Vec(IDL.Nat),
    'submittedAt' : Timestamp,
    'score' : IDL.Nat,
    'quizId' : QuizId,
  });
  const StudentPerformance = IDL.Record({
    'totalEnrollments' : IDL.Nat,
    'studentId' : UserId,
    'studentName' : IDL.Text,
    'averageQuizScore' : IDL.Float64,
    'completedLessons' : IDL.Nat,
    'quizzesTaken' : IDL.Nat,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
  });
  const QuestionWithAnswer = IDL.Record({
    'id' : QuestionId,
    'answerIndex' : IDL.Nat,
    'text' : IDL.Text,
    'quizId' : QuizId,
    'options' : IDL.Vec(IDL.Text),
  });
  const Result_3 = IDL.Variant({
    'ok' : IDL.Vec(QuestionWithAnswer),
    'err' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : UserProfilePublic, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'ok' : QuizAttempt, 'err' : IDL.Text });
  
  return IDL.Service({
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [Result_11], []),
    'createAssignment' : IDL.Func(
        [IDL.Opt(CourseId), IDL.Text, IDL.Text, IDL.Opt(Timestamp), IDL.Nat],
        [Result_10],
        [],
      ),
    'createCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_9], []),
    'createLesson' : IDL.Func(
        [CourseId, IDL.Text, IDL.Text, IDL.Nat],
        [Result_8],
        [],
      ),
    'createNote' : IDL.Func(
        [IDL.Opt(CourseId), IDL.Text, IDL.Text],
        [Result_7],
        [],
      ),
    'createQuestion' : IDL.Func(
        [QuizId, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [Result_6],
        [],
      ),
    'createQuiz' : IDL.Func([CourseId, IDL.Text, IDL.Text], [Result_5], []),
    'createScheduleSlot' : IDL.Func([ScheduleInput], [Result_4], []),
    'deleteAnnouncement' : IDL.Func([AnnouncementId], [Result], []),
    'deleteAssignment' : IDL.Func([AssignmentId], [Result], []),
    'deleteCourse' : IDL.Func([CourseId], [Result], []),
    'deleteLesson' : IDL.Func([LessonId], [Result], []),
    'deleteNote' : IDL.Func([NoteId], [Result], []),
    'deleteQuestion' : IDL.Func([QuestionId], [Result], []),
    'deleteQuiz' : IDL.Func([QuizId], [Result], []),
    'deleteScheduleSlot' : IDL.Func([ScheduleId], [Result], []),
    'enrollInCourse' : IDL.Func([CourseId], [Result], []),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEnrollments' : IDL.Nat,
            'totalStudents' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAssignment' : IDL.Func(
        [AssignmentId],
        [IDL.Opt(AssignmentPublic)],
        ['query'],
      ),
    'getCourse' : IDL.Func([CourseId], [IDL.Opt(CoursePublic)], ['query']),
    'getLesson' : IDL.Func([LessonId], [IDL.Opt(LessonPublic)], ['query']),
    'getMyAttempts' : IDL.Func(
        [IDL.Opt(QuizId)],
        [IDL.Vec(QuizAttempt)],
        ['query'],
      ),
    'getMyCompletedLessons' : IDL.Func([], [IDL.Vec(LessonId)], ['query']),
    'getMyEnrollments' : IDL.Func([], [IDL.Vec(CourseId)], ['query']),
    'getMyPerformance' : IDL.Func([], [IDL.Opt(StudentPerformance)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'getNote' : IDL.Func([NoteId], [IDL.Opt(NotePublic)], ['query']),
    'getQuiz' : IDL.Func([QuizId], [IDL.Opt(QuizPublic)], ['query']),
    'listAnnouncements' : IDL.Func(
        [],
        [IDL.Vec(AnnouncementPublic)],
        ['query'],
      ),
    'listAssignments' : IDL.Func(
        [IDL.Opt(CourseId)],
        [IDL.Vec(AssignmentPublic)],
        ['query'],
      ),
    'listCourses' : IDL.Func([], [IDL.Vec(CoursePublic)], ['query']),
    'listLessons' : IDL.Func([CourseId], [IDL.Vec(LessonPublic)], ['query']),
    'listNotes' : IDL.Func(
        [IDL.Opt(CourseId)],
        [IDL.Vec(NotePublic)],
        ['query'],
      ),
    'listQuestions' : IDL.Func([QuizId], [IDL.Vec(QuestionPublic)], ['query']),
    'listQuestionsWithAnswers' : IDL.Func([QuizId], [Result_3], []),
    'listQuizzes' : IDL.Func([CourseId], [IDL.Vec(QuizPublic)], ['query']),
    'listScheduleSlots' : IDL.Func(
        [],
        [IDL.Vec(ScheduleSlotPublic)],
        ['query'],
      ),
    'listScheduleSlotsByClass' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ScheduleSlotPublic)],
        ['query'],
      ),
    'listStudentPerformances' : IDL.Func(
        [],
        [IDL.Vec(StudentPerformance)],
        ['query'],
      ),
    'listUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
    'markAnnouncementRead' : IDL.Func([AnnouncementId], [Result], []),
    'markLessonComplete' : IDL.Func([LessonId], [Result], []),
    'register' : IDL.Func([IDL.Text], [Result_2], []),
    'registerAsAdmin' : IDL.Func([IDL.Text], [Result_2], []),
    'submitQuizAttempt' : IDL.Func([QuizId, IDL.Vec(IDL.Nat)], [Result_1], []),
    'updateAnnouncement' : IDL.Func(
        [AnnouncementId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
    'updateAssignment' : IDL.Func(
        [
          AssignmentId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(Timestamp),
          IDL.Opt(IDL.Nat),
        ],
        [Result],
        [],
      ),
    'updateCourse' : IDL.Func(
        [
          CourseId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
        ],
        [Result],
        [],
      ),
    'updateLesson' : IDL.Func(
        [LessonId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [Result],
        [],
      ),
    'updateNote' : IDL.Func(
        [NoteId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
    'updateQuestion' : IDL.Func(
        [
          QuestionId,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Text)),
          IDL.Opt(IDL.Nat),
        ],
        [Result],
        [],
      ),
    'updateQuiz' : IDL.Func(
        [QuizId, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
    'updateScheduleSlot' : IDL.Func([ScheduleId, ScheduleInput], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };