/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnnouncementId = bigint;
export interface AnnouncementPublic {
  'id' : AnnouncementId,
  'title' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'isRead' : boolean,
  'message' : string,
}
export type AssignmentId = bigint;
export interface AssignmentPublic {
  'id' : AssignmentId,
  'title' : string,
  'maxPoints' : bigint,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'dueDate' : [] | [Timestamp],
  'description' : string,
  'courseId' : [] | [CourseId],
}
export type CourseId = bigint;
export interface CoursePublic {
  'id' : CourseId,
  'title' : string,
  'published' : boolean,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'category' : string,
}
export type LessonId = bigint;
export interface LessonPublic {
  'id' : LessonId,
  'title' : string,
  'content' : string,
  'order' : bigint,
  'createdAt' : Timestamp,
  'courseId' : CourseId,
}
export type NoteId = bigint;
export interface NotePublic {
  'id' : NoteId,
  'title' : string,
  'content' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'updatedAt' : Timestamp,
  'courseId' : [] | [CourseId],
}
export type QuestionId = bigint;
export interface QuestionPublic {
  'id' : QuestionId,
  'text' : string,
  'quizId' : QuizId,
  'options' : Array<string>,
}
export interface QuestionWithAnswer {
  'id' : QuestionId,
  'answerIndex' : bigint,
  'text' : string,
  'quizId' : QuizId,
  'options' : Array<string>,
}
export interface QuizAttempt {
  'id' : bigint,
  'total' : bigint,
  'studentId' : UserId,
  'answers' : Array<bigint>,
  'submittedAt' : Timestamp,
  'score' : bigint,
  'quizId' : QuizId,
}
export type QuizId = bigint;
export interface QuizPublic {
  'id' : QuizId,
  'title' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'courseId' : CourseId,
}
export type Result = { 'ok' : boolean } |
  { 'err' : string };
export type Result_1 = { 'ok' : QuizAttempt } |
  { 'err' : string };
export type Result_10 = { 'ok' : AssignmentPublic } |
  { 'err' : string };
export type Result_11 = { 'ok' : AnnouncementPublic } |
  { 'err' : string };
export type Result_2 = { 'ok' : UserProfilePublic } |
  { 'err' : string };
export type Result_3 = { 'ok' : Array<QuestionWithAnswer> } |
  { 'err' : string };
export type Result_4 = { 'ok' : ScheduleSlotPublic } |
  { 'err' : string };
export type Result_5 = { 'ok' : QuizPublic } |
  { 'err' : string };
export type Result_6 = { 'ok' : QuestionPublic } |
  { 'err' : string };
export type Result_7 = { 'ok' : NotePublic } |
  { 'err' : string };
export type Result_8 = { 'ok' : LessonPublic } |
  { 'err' : string };
export type Result_9 = { 'ok' : CoursePublic } |
  { 'err' : string };
export type Role = { 'admin' : null } |
  { 'student' : null };
export type ScheduleId = bigint;
export interface ScheduleInput {
  'day' : string,
  'subject' : string,
  'teacher' : string,
  'timeRange' : string,
  'className' : string,
  'timeSlot' : string,
}
export interface ScheduleSlotPublic {
  'id' : ScheduleId,
  'day' : string,
  'subject' : string,
  'createdAt' : Timestamp,
  'teacher' : string,
  'isActive' : boolean,
  'timeRange' : string,
  'className' : string,
  'timeSlot' : string,
}
export interface StudentPerformance {
  'totalEnrollments' : bigint,
  'studentId' : UserId,
  'studentName' : string,
  'averageQuizScore' : number,
  'completedLessons' : bigint,
  'quizzesTaken' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
}
export interface _SERVICE {
  'createAnnouncement' : ActorMethod<[string, string], Result_11>,
  'createAssignment' : ActorMethod<
    [[] | [CourseId], string, string, [] | [Timestamp], bigint],
    Result_10
  >,
  'createCourse' : ActorMethod<[string, string, string], Result_9>,
  'createLesson' : ActorMethod<[CourseId, string, string, bigint], Result_8>,
  'createNote' : ActorMethod<[[] | [CourseId], string, string], Result_7>,
  'createQuestion' : ActorMethod<
    [QuizId, string, Array<string>, bigint],
    Result_6
  >,
  'createQuiz' : ActorMethod<[CourseId, string, string], Result_5>,
  'createScheduleSlot' : ActorMethod<[ScheduleInput], Result_4>,
  'deleteAnnouncement' : ActorMethod<[AnnouncementId], Result>,
  'deleteAssignment' : ActorMethod<[AssignmentId], Result>,
  'deleteCourse' : ActorMethod<[CourseId], Result>,
  'deleteLesson' : ActorMethod<[LessonId], Result>,
  'deleteNote' : ActorMethod<[NoteId], Result>,
  'deleteQuestion' : ActorMethod<[QuestionId], Result>,
  'deleteQuiz' : ActorMethod<[QuizId], Result>,
  'deleteScheduleSlot' : ActorMethod<[ScheduleId], Result>,
  'enrollInCourse' : ActorMethod<[CourseId], Result>,
  'getAdminStats' : ActorMethod<
    [],
    { 'totalEnrollments' : bigint, 'totalStudents' : bigint }
  >,
  'getAssignment' : ActorMethod<[AssignmentId], [] | [AssignmentPublic]>,
  'getCourse' : ActorMethod<[CourseId], [] | [CoursePublic]>,
  'getLesson' : ActorMethod<[LessonId], [] | [LessonPublic]>,
  'getMyAttempts' : ActorMethod<[[] | [QuizId]], Array<QuizAttempt>>,
  'getMyCompletedLessons' : ActorMethod<[], Array<LessonId>>,
  'getMyEnrollments' : ActorMethod<[], Array<CourseId>>,
  'getMyPerformance' : ActorMethod<[], [] | [StudentPerformance]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getNote' : ActorMethod<[NoteId], [] | [NotePublic]>,
  'getQuiz' : ActorMethod<[QuizId], [] | [QuizPublic]>,
  'listAnnouncements' : ActorMethod<[], Array<AnnouncementPublic>>,
  'listAssignments' : ActorMethod<[[] | [CourseId]], Array<AssignmentPublic>>,
  'listCourses' : ActorMethod<[], Array<CoursePublic>>,
  'listLessons' : ActorMethod<[CourseId], Array<LessonPublic>>,
  'listNotes' : ActorMethod<[[] | [CourseId]], Array<NotePublic>>,
  'listQuestions' : ActorMethod<[QuizId], Array<QuestionPublic>>,
  'listQuestionsWithAnswers' : ActorMethod<[QuizId], Result_3>,
  'listQuizzes' : ActorMethod<[CourseId], Array<QuizPublic>>,
  'listScheduleSlots' : ActorMethod<[], Array<ScheduleSlotPublic>>,
  'listScheduleSlotsByClass' : ActorMethod<[string], Array<ScheduleSlotPublic>>,
  'listStudentPerformances' : ActorMethod<[], Array<StudentPerformance>>,
  'listUsers' : ActorMethod<[], Array<UserProfilePublic>>,
  'markAnnouncementRead' : ActorMethod<[AnnouncementId], Result>,
  'markLessonComplete' : ActorMethod<[LessonId], Result>,
  'register' : ActorMethod<[string], Result_2>,
  'registerAsAdmin' : ActorMethod<[string], Result_2>,
  'submitQuizAttempt' : ActorMethod<[QuizId, Array<bigint>], Result_1>,
  'updateAnnouncement' : ActorMethod<
    [AnnouncementId, [] | [string], [] | [string]],
    Result
  >,
  'updateAssignment' : ActorMethod<
    [
      AssignmentId,
      [] | [string],
      [] | [string],
      [] | [Timestamp],
      [] | [bigint],
    ],
    Result
  >,
  'updateCourse' : ActorMethod<
    [CourseId, [] | [string], [] | [string], [] | [string], [] | [boolean]],
    Result
  >,
  'updateLesson' : ActorMethod<
    [LessonId, [] | [string], [] | [string], [] | [bigint]],
    Result
  >,
  'updateNote' : ActorMethod<[NoteId, [] | [string], [] | [string]], Result>,
  'updateQuestion' : ActorMethod<
    [QuestionId, [] | [string], [] | [Array<string>], [] | [bigint]],
    Result
  >,
  'updateQuiz' : ActorMethod<[QuizId, [] | [string], [] | [string]], Result>,
  'updateScheduleSlot' : ActorMethod<[ScheduleId, ScheduleInput], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];