/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StudentPerformance {
    totalEnrollments: bigint;
    studentId: UserId;
    studentName: string;
    averageQuizScore: number;
    completedLessons: bigint;
    quizzesTaken: bigint;
}
export type Timestamp = bigint;
export interface ScheduleInput {
    day: string;
    subject: string;
    teacher: string;
    timeRange: string;
    className: string;
    timeSlot: string;
}
export type Result_2 = {
    __kind__: "ok";
    ok: UserProfilePublic;
} | {
    __kind__: "err";
    err: string;
};
export interface QuestionPublic {
    id: QuestionId;
    text: string;
    quizId: QuizId;
    options: Array<string>;
}
export interface QuizPublic {
    id: QuizId;
    title: string;
    createdAt: Timestamp;
    createdBy: UserId;
    description: string;
    courseId: CourseId;
}
export interface AssignmentPublic {
    id: AssignmentId;
    title: string;
    maxPoints: bigint;
    createdAt: Timestamp;
    createdBy: UserId;
    dueDate?: Timestamp;
    description: string;
    courseId?: CourseId;
}
export type Result_5 = {
    __kind__: "ok";
    ok: QuizPublic;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: QuizAttempt;
} | {
    __kind__: "err";
    err: string;
};
export type Result_4 = {
    __kind__: "ok";
    ok: ScheduleSlotPublic;
} | {
    __kind__: "err";
    err: string;
};
export type Result_11 = {
    __kind__: "ok";
    ok: AnnouncementPublic;
} | {
    __kind__: "err";
    err: string;
};
export interface QuizAttempt {
    id: bigint;
    total: bigint;
    studentId: UserId;
    answers: Array<bigint>;
    submittedAt: Timestamp;
    score: bigint;
    quizId: QuizId;
}
export type CourseId = bigint;
export type Result_7 = {
    __kind__: "ok";
    ok: NotePublic;
} | {
    __kind__: "err";
    err: string;
};
export type AssignmentId = bigint;
export interface ScheduleSlotPublic {
    id: ScheduleId;
    day: string;
    subject: string;
    createdAt: Timestamp;
    teacher: string;
    isActive: boolean;
    timeRange: string;
    className: string;
    timeSlot: string;
}
export interface NotePublic {
    id: NoteId;
    title: string;
    content: string;
    createdAt: Timestamp;
    createdBy: UserId;
    updatedAt: Timestamp;
    courseId?: CourseId;
}
export type NoteId = bigint;
export interface CoursePublic {
    id: CourseId;
    title: string;
    published: boolean;
    createdAt: Timestamp;
    createdBy: UserId;
    description: string;
    category: string;
}
export type Result_6 = {
    __kind__: "ok";
    ok: QuestionPublic;
} | {
    __kind__: "err";
    err: string;
};
export type LessonId = bigint;
export interface AnnouncementPublic {
    id: AnnouncementId;
    title: string;
    createdAt: Timestamp;
    createdBy: UserId;
    isRead: boolean;
    message: string;
}
export type QuestionId = bigint;
export interface LessonPublic {
    id: LessonId;
    title: string;
    content: string;
    order: bigint;
    createdAt: Timestamp;
    courseId: CourseId;
}
export type Result_9 = {
    __kind__: "ok";
    ok: CoursePublic;
} | {
    __kind__: "err";
    err: string;
};
export interface UserProfilePublic {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: Role;
}
export type UserId = Principal;
export type ScheduleId = bigint;
export type Result = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: Array<QuestionWithAnswer>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_10 = {
    __kind__: "ok";
    ok: AssignmentPublic;
} | {
    __kind__: "err";
    err: string;
};
export type Result_8 = {
    __kind__: "ok";
    ok: LessonPublic;
} | {
    __kind__: "err";
    err: string;
};
export type AnnouncementId = bigint;
export interface QuestionWithAnswer {
    id: QuestionId;
    answerIndex: bigint;
    text: string;
    quizId: QuizId;
    options: Array<string>;
}
export type QuizId = bigint;
export enum Role {
    admin = "admin",
    student = "student"
}
export interface backendInterface {
    createAnnouncement(title: string, message: string): Promise<Result_11>;
    createAssignment(courseId: CourseId | null, title: string, description: string, dueDate: Timestamp | null, maxPoints: bigint): Promise<Result_10>;
    createCourse(title: string, description: string, category: string): Promise<Result_9>;
    createLesson(courseId: CourseId, title: string, content: string, order: bigint): Promise<Result_8>;
    createNote(courseId: CourseId | null, title: string, content: string): Promise<Result_7>;
    createQuestion(quizId: QuizId, text: string, options: Array<string>, answerIndex: bigint): Promise<Result_6>;
    createQuiz(courseId: CourseId, title: string, description: string): Promise<Result_5>;
    createScheduleSlot(input: ScheduleInput): Promise<Result_4>;
    deleteAnnouncement(id: AnnouncementId): Promise<Result>;
    deleteAssignment(id: AssignmentId): Promise<Result>;
    deleteCourse(id: CourseId): Promise<Result>;
    deleteLesson(id: LessonId): Promise<Result>;
    deleteNote(id: NoteId): Promise<Result>;
    deleteQuestion(id: QuestionId): Promise<Result>;
    deleteQuiz(id: QuizId): Promise<Result>;
    deleteScheduleSlot(id: ScheduleId): Promise<Result>;
    enrollInCourse(courseId: CourseId): Promise<Result>;
    getAdminStats(): Promise<{
        totalEnrollments: bigint;
        totalStudents: bigint;
    }>;
    getAssignment(id: AssignmentId): Promise<AssignmentPublic | null>;
    getCourse(id: CourseId): Promise<CoursePublic | null>;
    getLesson(id: LessonId): Promise<LessonPublic | null>;
    getMyAttempts(quizId: QuizId | null): Promise<Array<QuizAttempt>>;
    getMyCompletedLessons(): Promise<Array<LessonId>>;
    getMyEnrollments(): Promise<Array<CourseId>>;
    getMyPerformance(): Promise<StudentPerformance | null>;
    getMyProfile(): Promise<UserProfilePublic | null>;
    getNote(id: NoteId): Promise<NotePublic | null>;
    getQuiz(id: QuizId): Promise<QuizPublic | null>;
    listAnnouncements(): Promise<Array<AnnouncementPublic>>;
    listAssignments(courseId: CourseId | null): Promise<Array<AssignmentPublic>>;
    listCourses(): Promise<Array<CoursePublic>>;
    listLessons(courseId: CourseId): Promise<Array<LessonPublic>>;
    listNotes(courseId: CourseId | null): Promise<Array<NotePublic>>;
    listQuestions(quizId: QuizId): Promise<Array<QuestionPublic>>;
    listQuestionsWithAnswers(quizId: QuizId): Promise<Result_3>;
    listQuizzes(courseId: CourseId): Promise<Array<QuizPublic>>;
    listScheduleSlots(): Promise<Array<ScheduleSlotPublic>>;
    listScheduleSlotsByClass(className: string): Promise<Array<ScheduleSlotPublic>>;
    listStudentPerformances(): Promise<Array<StudentPerformance>>;
    listUsers(): Promise<Array<UserProfilePublic>>;
    markAnnouncementRead(id: AnnouncementId): Promise<Result>;
    markLessonComplete(lessonId: LessonId): Promise<Result>;
    register(name: string): Promise<Result_2>;
    registerAsAdmin(name: string): Promise<Result_2>;
    submitQuizAttempt(quizId: QuizId, answers: Array<bigint>): Promise<Result_1>;
    updateAnnouncement(id: AnnouncementId, title: string | null, message: string | null): Promise<Result>;
    updateAssignment(id: AssignmentId, title: string | null, description: string | null, dueDate: Timestamp | null, maxPoints: bigint | null): Promise<Result>;
    updateCourse(id: CourseId, title: string | null, description: string | null, category: string | null, published: boolean | null): Promise<Result>;
    updateLesson(id: LessonId, title: string | null, content: string | null, order: bigint | null): Promise<Result>;
    updateNote(id: NoteId, title: string | null, content: string | null): Promise<Result>;
    updateQuestion(id: QuestionId, text: string | null, options: Array<string> | null, answerIndex: bigint | null): Promise<Result>;
    updateQuiz(id: QuizId, title: string | null, description: string | null): Promise<Result>;
    updateScheduleSlot(id: ScheduleId, input: ScheduleInput): Promise<Result>;
}
import type { AnnouncementPublic as _AnnouncementPublic, AssignmentId as _AssignmentId, AssignmentPublic as _AssignmentPublic, CourseId as _CourseId, CoursePublic as _CoursePublic, LessonPublic as _LessonPublic, NoteId as _NoteId, NotePublic as _NotePublic, QuestionPublic as _QuestionPublic, QuestionWithAnswer as _QuestionWithAnswer, QuizAttempt as _QuizAttempt, QuizId as _QuizId, QuizPublic as _QuizPublic, Result as _Result, Result_1 as _Result_1, Result_10 as _Result_10, Result_11 as _Result_11, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, Role as _Role, ScheduleSlotPublic as _ScheduleSlotPublic, StudentPerformance as _StudentPerformance, Timestamp as _Timestamp, UserId as _UserId, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAnnouncement(arg0: string, arg1: string): Promise<Result_11> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(arg0, arg1);
                return from_candid_Result_11_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(arg0, arg1);
            return from_candid_Result_11_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createAssignment(arg0: CourseId | null, arg1: string, arg2: string, arg3: Timestamp | null, arg4: bigint): Promise<Result_10> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssignment(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Result_10_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssignment(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Result_10_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCourse(arg0: string, arg1: string, arg2: string): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.createCourse(arg0, arg1, arg2);
                return from_candid_Result_9_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCourse(arg0, arg1, arg2);
            return from_candid_Result_9_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLesson(arg0: CourseId, arg1: string, arg2: string, arg3: bigint): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.createLesson(arg0, arg1, arg2, arg3);
                return from_candid_Result_8_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLesson(arg0, arg1, arg2, arg3);
            return from_candid_Result_8_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNote(arg0: CourseId | null, arg1: string, arg2: string): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_Result_7_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_Result_7_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createQuestion(arg0: QuizId, arg1: string, arg2: Array<string>, arg3: bigint): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuestion(arg0, arg1, arg2, arg3);
                return from_candid_Result_6_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuestion(arg0, arg1, arg2, arg3);
            return from_candid_Result_6_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async createQuiz(arg0: CourseId, arg1: string, arg2: string): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuiz(arg0, arg1, arg2);
                return from_candid_Result_5_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuiz(arg0, arg1, arg2);
            return from_candid_Result_5_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createScheduleSlot(arg0: ScheduleInput): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.createScheduleSlot(arg0);
                return from_candid_Result_4_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScheduleSlot(arg0);
            return from_candid_Result_4_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAnnouncement(arg0: AnnouncementId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAssignment(arg0: AssignmentId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssignment(arg0);
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssignment(arg0);
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCourse(arg0: CourseId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteLesson(arg0: LessonId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLesson(arg0);
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLesson(arg0);
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteNote(arg0: NoteId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteQuestion(arg0: QuestionId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestion(arg0);
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestion(arg0);
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteQuiz(arg0: QuizId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuiz(arg0);
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuiz(arg0);
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteScheduleSlot(arg0: ScheduleId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScheduleSlot(arg0);
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScheduleSlot(arg0);
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async enrollInCourse(arg0: CourseId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollInCourse(arg0);
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollInCourse(arg0);
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<{
        totalEnrollments: bigint;
        totalStudents: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAssignment(arg0: AssignmentId): Promise<AssignmentPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignment(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignment(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: CourseId): Promise<CoursePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLesson(arg0: LessonId): Promise<LessonPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLesson(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLesson(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAttempts(arg0: QuizId | null): Promise<Array<QuizAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAttempts(to_candid_opt_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAttempts(to_candid_opt_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getMyCompletedLessons(): Promise<Array<LessonId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCompletedLessons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCompletedLessons();
            return result;
        }
    }
    async getMyEnrollments(): Promise<Array<CourseId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEnrollments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEnrollments();
            return result;
        }
    }
    async getMyPerformance(): Promise<StudentPerformance | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPerformance();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPerformance();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNote(arg0: NoteId): Promise<NotePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuiz(arg0: QuizId): Promise<QuizPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuiz(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuiz(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAnnouncements(): Promise<Array<AnnouncementPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnnouncements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnnouncements();
            return result;
        }
    }
    async listAssignments(arg0: CourseId | null): Promise<Array<AssignmentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssignments(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssignments(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCourses(): Promise<Array<CoursePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCourses();
            return result;
        }
    }
    async listLessons(arg0: CourseId): Promise<Array<LessonPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLessons(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLessons(arg0);
            return result;
        }
    }
    async listNotes(arg0: CourseId | null): Promise<Array<NotePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotes(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotes(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async listQuestions(arg0: QuizId): Promise<Array<QuestionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuestions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuestions(arg0);
            return result;
        }
    }
    async listQuestionsWithAnswers(arg0: QuizId): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuestionsWithAnswers(arg0);
                return from_candid_Result_3_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuestionsWithAnswers(arg0);
            return from_candid_Result_3_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listQuizzes(arg0: CourseId): Promise<Array<QuizPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuizzes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuizzes(arg0);
            return result;
        }
    }
    async listScheduleSlots(): Promise<Array<ScheduleSlotPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listScheduleSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listScheduleSlots();
            return result;
        }
    }
    async listScheduleSlotsByClass(arg0: string): Promise<Array<ScheduleSlotPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listScheduleSlotsByClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listScheduleSlotsByClass(arg0);
            return result;
        }
    }
    async listStudentPerformances(): Promise<Array<StudentPerformance>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudentPerformances();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudentPerformances();
            return result;
        }
    }
    async listUsers(): Promise<Array<UserProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAnnouncementRead(arg0: AnnouncementId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.markAnnouncementRead(arg0);
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAnnouncementRead(arg0);
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async markLessonComplete(arg0: LessonId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.markLessonComplete(arg0);
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markLessonComplete(arg0);
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0);
                return from_candid_Result_2_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0);
            return from_candid_Result_2_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerAsAdmin(arg0: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAsAdmin(arg0);
                return from_candid_Result_2_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAsAdmin(arg0);
            return from_candid_Result_2_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitQuizAttempt(arg0: QuizId, arg1: Array<bigint>): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAttempt(arg0, arg1);
                return from_candid_Result_1_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAttempt(arg0, arg1);
            return from_candid_Result_1_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAnnouncement(arg0: AnnouncementId, arg1: string | null, arg2: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnouncement(arg0, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnouncement(arg0, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAssignment(arg0: AssignmentId, arg1: string | null, arg2: string | null, arg3: Timestamp | null, arg4: bigint | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssignment(arg0, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssignment(arg0, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCourse(arg0: CourseId, arg1: string | null, arg2: string | null, arg3: string | null, arg4: boolean | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLesson(arg0: LessonId, arg1: string | null, arg2: string | null, arg3: bigint | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLesson(arg0, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLesson(arg0, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNote(arg0: NoteId, arg1: string | null, arg2: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateQuestion(arg0: QuestionId, arg1: string | null, arg2: Array<string> | null, arg3: bigint | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestion(arg0, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n51(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestion(arg0, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n51(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n49(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateQuiz(arg0: QuizId, arg1: string | null, arg2: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuiz(arg0, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuiz(arg0, to_candid_opt_n48(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateScheduleSlot(arg0: ScheduleId, arg1: ScheduleInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScheduleSlot(arg0, arg1);
                return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScheduleSlot(arg0, arg1);
            return from_candid_Result_n25(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AssignmentPublic_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssignmentPublic): AssignmentPublic {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_NotePublic_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotePublic): NotePublic {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Result_10_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_10): Result_10 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_11_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_11): Result_11 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Result_8_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_8): Result_8 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Result_9_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_9): Result_9 {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CourseId]): CourseId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AssignmentPublic]): AssignmentPublic | null {
    return value.length === 0 ? null : from_candid_AssignmentPublic_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CoursePublic]): CoursePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LessonPublic]): LessonPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentPerformance]): StudentPerformance | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NotePublic]): NotePublic | null {
    return value.length === 0 ? null : from_candid_NotePublic_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizPublic]): QuizPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NoteId;
    title: string;
    content: string;
    createdAt: _Timestamp;
    createdBy: _UserId;
    updatedAt: _Timestamp;
    courseId: [] | [_CourseId];
}): {
    id: NoteId;
    title: string;
    content: string;
    createdAt: Timestamp;
    createdBy: UserId;
    updatedAt: Timestamp;
    courseId?: CourseId;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        updatedAt: value.updatedAt,
        courseId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.courseId))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: Role;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n35(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AssignmentId;
    title: string;
    maxPoints: bigint;
    createdAt: _Timestamp;
    createdBy: _UserId;
    dueDate: [] | [_Timestamp];
    description: string;
    courseId: [] | [_CourseId];
}): {
    id: AssignmentId;
    title: string;
    maxPoints: bigint;
    createdAt: Timestamp;
    createdBy: UserId;
    dueDate?: Timestamp;
    description: string;
    courseId?: CourseId;
} {
    return {
        id: value.id,
        title: value.title,
        maxPoints: value.maxPoints,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        dueDate: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description,
        courseId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.courseId))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CoursePublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CoursePublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LessonPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: LessonPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _NotePublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: NotePublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_NotePublic_n17(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AnnouncementPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AnnouncementPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _QuestionPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: QuestionPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _QuizPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: QuizPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ScheduleSlotPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ScheduleSlotPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    student: null;
}): Role {
    return "admin" in value ? Role.admin : "student" in value ? Role.student : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_QuestionWithAnswer>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<QuestionWithAnswer>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfilePublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfilePublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfilePublic_n33(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _QuizAttempt;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: QuizAttempt;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AssignmentPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AssignmentPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AssignmentPublic_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssignmentPublic>): Array<AssignmentPublic> {
    return value.map((x)=>from_candid_AssignmentPublic_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotePublic>): Array<NotePublic> {
    return value.map((x)=>from_candid_NotePublic_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfilePublic>): Array<UserProfilePublic> {
    return value.map((x)=>from_candid_UserProfilePublic_n33(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CourseId | null): [] | [_CourseId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuizId | null): [] | [_QuizId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<string> | null): [] | [Array<string>] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
